pwm:
  frequency_hz: 10000
  pins:
    "12": { duty_percent: 70 } # HVM 1
    "13": { duty_percent: 70 } # HVM 2

sequence:
  # SLDEAs Pin 27
  - type: pwm_start
  - type: sleep
    duration: 1.0
  - type: gpio_high
    pin: 27
    duration: 1.0
  - type: gpio_low
    pin: 27
  - type: sleep
    duration: 1.0
  - type: pwm_stop
    duration: 0.0

  # Grippers Pin 23
  - type: pwm_start
  - type: sleep
    duration: 1.0
  - type: gpio_high
    pin: 23
    duration: 3.0
  - type: gpio_low
    pin: 23
  - type: sleep
    duration: 1.0
  - type: pwm_stop
    duration: 0.0

  # Wait between loops
  - type: sleep
    pin: null
    duration: 5.0
