pwm:
  frequency_hz: 10000        # PWM frequency for both hardware PWM pins
  pins:
    "13":
      duty_percent: 90      # Duty cycle for BCM 13
    "12":
      duty_percent: 90      # Duty cycle for BCM 12

sequence:
  # Phase 1: PWM on BCM 13, then 23/24 toggles
  # - type: pwm_start
  #   pin: 13
  #   duration: 0.0

  - type: pwm_start # HVM 2
    pin: 13
    duration: 0.0

  - type: gpio_high
    pin: 23
    duration: 5.0

  - type: gpio_low
    pin: 23
    duration: 0.0

  - type: gpio_high
    pin: 24
    duration: 5.0

  - type: gpio_low
    pin: 24
    duration: 0.0

  - type: pwm_stop
    pin: 13
    duration: 0.0



  - type: pwm_start # HVM 1
    pin: 12
    duration: 0.0

  - type: gpio_high
    pin: 22
    duration: 3.0

  - type: gpio_low
    pin: 22
    duration: 0.0

  - type: gpio_high
    pin: 27
    duration: 3.0

  - type: gpio_low
    pin: 27
    duration: 0.0

  - type: pwm_stop
    pin: 12
    duration: 0.0



  # Wait between loops
  - type: sleep
    pin: null
    duration: 5.0

